### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by AngledLuffa** [nickyringland/nested_named_entities#6]
Is there a license, such as CC, MIT, etc, for the named entity annotations in this work?  I would like to add it to the chart at https://github.com/juand-r/entity-recognition-datasets, and the English chart has licenses, generally speaking.  Thanks!

**Comment by dainlp** [comment]
Hi, I have added the LICENSE file and updated the README.md file

**Comment by AngledLuffa** [comment]
Thank you!  That was exactly what we needed.
